/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package layout;

import classtables.Professor;
import com.sun.org.apache.xerces.internal.xs.StringList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import query.ProfessorQ;

/**
 *
 * @author heitor
 */
public class ProfessorW extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     */
    public ProfessorW(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_delete = new javax.swing.JButton();
        bt_name = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        professor_table = new javax.swing.JTable();
        bt_id = new javax.swing.JTextField();
        bt_save = new javax.swing.JButton();
        bt_update = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Professor");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        bt_delete.setText("Delete");
        bt_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_deleteActionPerformed(evt);
            }
        });

        bt_name.setBorder(javax.swing.BorderFactory.createTitledBorder("Name"));
        bt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_nameActionPerformed(evt);
            }
        });

        professor_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name"
            }
        ));
        professor_table.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                professor_tableComponentAdded(evt);
            }
        });
        professor_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                professor_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(professor_table);

        bt_id.setEditable(false);
        bt_id.setBorder(javax.swing.BorderFactory.createTitledBorder("ID"));
        bt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_idActionPerformed(evt);
            }
        });

        bt_save.setText("Save");
        bt_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_saveActionPerformed(evt);
            }
        });

        bt_update.setText("Update");
        bt_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_updateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_save, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(164, 164, 164)
                        .addComponent(bt_update, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(bt_delete)
                            .addComponent(bt_save)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(bt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_update))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_deleteActionPerformed
        Remove();
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_deleteActionPerformed

    private void bt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_nameActionPerformed

    private void professor_tableComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_professor_tableComponentAdded

    }//GEN-LAST:event_professor_tableComponentAdded

    private void bt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_idActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        List();
    }//GEN-LAST:event_formWindowOpened

    private void bt_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_saveActionPerformed
        Save();
    }//GEN-LAST:event_bt_saveActionPerformed

    private void professor_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_professor_tableMouseClicked
        bt_id.setText(String.valueOf(professor_table.getValueAt(professor_table.getSelectedRow(), 0)));
        bt_name.setText(String.valueOf(professor_table.getValueAt(professor_table.getSelectedRow(), 1)));
    }//GEN-LAST:event_professor_tableMouseClicked

    private void bt_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_updateActionPerformed
        Update();
    }//GEN-LAST:event_bt_updateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfessorW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfessorW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfessorW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfessorW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ProfessorW dialog = new ProfessorW(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_delete;
    private javax.swing.JTextField bt_id;
    private javax.swing.JTextField bt_name;
    private javax.swing.JButton bt_save;
    private javax.swing.JButton bt_update;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable professor_table;
    // End of variables declaration//GEN-END:variables
    void Save(){
        try{
            Professor professor = new Professor();
            professor.setP_name(bt_name.getText());
            ProfessorQ q = new ProfessorQ();
            q.AddProfessor(professor);
            List();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
    }
    
    void List(){
        try{
            Professor professor = new Professor();
            professor.setP_name(bt_name.getText());
            ProfessorQ q = new ProfessorQ();
            List<Professor> list= q.ListProfessors();
            DefaultTableModel model = (DefaultTableModel)professor_table.getModel();
            model.setRowCount(0);
            for(Professor s : list){
                model.addRow(new Object[]{s.getP_id(),s.getP_name()});
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
    }
    void Remove(){
        try{
            Professor professor = new Professor();
            professor.setP_id(Integer.parseInt(bt_id.getText()));
            ProfessorQ q = new ProfessorQ();
            q.RemoveProfessor(professor);
            List();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
    }
    void Update(){
        try{
            Professor professor = new Professor();
            professor.setP_id(Integer.parseInt(bt_id.getText()));
            professor.setP_name(bt_name.getText());
            ProfessorQ q = new ProfessorQ();
            q.UpdateProfessor(professor);
            List();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
}
