/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package layout;

import classtables.Registration;
import classtables.Student;
import classtables.Subject;
import com.sun.org.apache.xerces.internal.xs.StringList;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import query.RegistrationQ;
import query.StudentQ;
import query.SubjectQ;

/**
 *
 * @author heitor
 */
public class RegistrationW extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     */
    public RegistrationW(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cb_student_id = new javax.swing.JComboBox<>();
        cb_subject_id = new javax.swing.JComboBox<>();
        bt_delete = new javax.swing.JButton();
        txt_id_subject = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        registration_table = new javax.swing.JTable();
        txt_id_student = new javax.swing.JTextField();
        bt_save = new javax.swing.JButton();
        cb_student = new javax.swing.JComboBox<>();
        cb_subject = new javax.swing.JComboBox<>();
        bt_clear = new javax.swing.JButton();

        cb_subject_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_subject_idActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        bt_delete.setText("Delete");
        bt_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_deleteActionPerformed(evt);
            }
        });

        txt_id_subject.setBorder(javax.swing.BorderFactory.createTitledBorder("Subject ID"));
        txt_id_subject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id_subjectActionPerformed(evt);
            }
        });

        registration_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "Subject ID"
            }
        ));
        registration_table.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                registration_tableComponentAdded(evt);
            }
        });
        registration_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registration_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(registration_table);

        txt_id_student.setBorder(javax.swing.BorderFactory.createTitledBorder("Student ID"));
        txt_id_student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id_studentActionPerformed(evt);
            }
        });

        bt_save.setText("Save");
        bt_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_saveActionPerformed(evt);
            }
        });

        cb_student.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_studentItemStateChanged(evt);
            }
        });

        cb_subject.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_subjectItemStateChanged(evt);
            }
        });
        cb_subject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_subjectActionPerformed(evt);
            }
        });

        bt_clear.setText("Clear");
        bt_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_clearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_id_subject, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_subject, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_id_student, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_student, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addComponent(bt_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_clear, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(bt_save)
                            .addComponent(bt_delete)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_id_student, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_student, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_id_subject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cb_subject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bt_clear))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_deleteActionPerformed
        Remove();
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_deleteActionPerformed

    private void txt_id_subjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id_subjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id_subjectActionPerformed

    private void registration_tableComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_registration_tableComponentAdded

    }//GEN-LAST:event_registration_tableComponentAdded

    private void txt_id_studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id_studentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id_studentActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        StudentQ sq = new StudentQ();
        List<Student> slist = sq.ListStudents();
        //Students combo box include
        for(Student tempstudent : slist){
            cb_student.addItem(tempstudent.getS_name());
            cb_student_id.addItem(String.valueOf(tempstudent.getS_id()));
        }
        SubjectQ suq = new SubjectQ();
        List<Subject> sulist = suq.ListSubjects();
        //Subjects combo box include
        for(Subject tempsubject : sulist){
            cb_subject.addItem(tempsubject.getSu_name());
            cb_subject_id.addItem(String.valueOf(tempsubject.getSu_id()));
        }
        cb_subject.setSelectedIndex(-1);
        cb_student.setSelectedIndex(-1);
        List();
    }//GEN-LAST:event_formWindowOpened

    private void bt_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_saveActionPerformed
        Save();
    }//GEN-LAST:event_bt_saveActionPerformed

    private void registration_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registration_tableMouseClicked
        txt_id_student.setText(String.valueOf(registration_table.getValueAt(registration_table.getSelectedRow(), 0)));
        txt_id_subject.setText(String.valueOf(registration_table.getValueAt(registration_table.getSelectedRow(), 1)));
    }//GEN-LAST:event_registration_tableMouseClicked

    private void cb_subjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_subjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_subjectActionPerformed

    private void cb_subject_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_subject_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_subject_idActionPerformed

    private void cb_studentItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_studentItemStateChanged
        txt_id_student.setText(String.valueOf(cb_student_id.getItemAt(cb_student.getSelectedIndex())));
        
    }//GEN-LAST:event_cb_studentItemStateChanged

    private void cb_subjectItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_subjectItemStateChanged
        txt_id_subject.setText(String.valueOf(cb_subject_id.getItemAt(cb_subject.getSelectedIndex())));
    }//GEN-LAST:event_cb_subjectItemStateChanged

    private void bt_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_clearActionPerformed
        Clear();
    }//GEN-LAST:event_bt_clearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RegistrationW dialog = new RegistrationW(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_clear;
    private javax.swing.JButton bt_delete;
    private javax.swing.JButton bt_save;
    private javax.swing.JComboBox<String> cb_student;
    private javax.swing.JComboBox<String> cb_student_id;
    private javax.swing.JComboBox<String> cb_subject;
    private javax.swing.JComboBox<String> cb_subject_id;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable registration_table;
    private javax.swing.JTextField txt_id_student;
    private javax.swing.JTextField txt_id_subject;
    // End of variables declaration//GEN-END:variables
    void Save(){
        try{
            Registration student = new Registration();
            student.setSu_id(Integer.parseInt(txt_id_subject.getText()));
            student.setS_id(Integer.parseInt(txt_id_student.getText()));
            RegistrationQ q = new RegistrationQ();
            q.AddRegistration(student);
            List();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
    }
    
    void List(){
        try{
            Registration student = new Registration();
            RegistrationQ q = new RegistrationQ();
            List<Registration> list= q.ListRegistrations();
            DefaultTableModel model = (DefaultTableModel)registration_table.getModel();
            model.setRowCount(0);
            for(Registration s : list){
                model.addRow(new Object[]{s.getS_id(),s.getSu_id()});
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
    }
    void Remove(){
        try{
            Registration student = new Registration();
            student.setS_id(Integer.parseInt(txt_id_student.getText()));
            student.setSu_id(Integer.parseInt(txt_id_subject.getText()));
            RegistrationQ q = new RegistrationQ();
            q.RemoveRegistration(student);
            List();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
    }
    void Update(){
        try{
            Registration student = new Registration();
            student.setS_id(Integer.parseInt(txt_id_student.getText()));
            student.setSu_id(Integer.parseInt(txt_id_subject.getText()));
            RegistrationQ s = new RegistrationQ();
            s.UpdateRegistration(student);
            List();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }
    
    void Clear(){
        
        txt_id_student.setText(null);
        txt_id_subject.setText(null);
        cb_student.setSelectedIndex(-1);
        cb_subject.setSelectedIndex(-1);
    }
}
