/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package layout;

import classtables.Professor;
import com.sun.org.apache.xerces.internal.xs.StringList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import query.SubjectQ;
import classtables.Subject;
import query.ProfessorQ;
/**
 *
 * @author heitor
 */
public class SubjectW extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     */
    public SubjectW(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cb_p_id = new javax.swing.JComboBox<>();
        bt_delete = new javax.swing.JButton();
        bt_name = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        subject_table = new javax.swing.JTable();
        bt_id = new javax.swing.JTextField();
        bt_save = new javax.swing.JButton();
        bt_update = new javax.swing.JButton();
        bt_description = new javax.swing.JTextField();
        bt_p_id = new javax.swing.JTextField();
        cb_p_name = new javax.swing.JComboBox<>();
        bt_clear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Subject");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        bt_delete.setText("Delete");
        bt_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_deleteActionPerformed(evt);
            }
        });

        bt_name.setBorder(javax.swing.BorderFactory.createTitledBorder("Name"));
        bt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_nameActionPerformed(evt);
            }
        });

        subject_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Description", "Professor ID"
            }
        ));
        subject_table.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                subject_tableComponentAdded(evt);
            }
        });
        subject_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subject_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(subject_table);

        bt_id.setEditable(false);
        bt_id.setBorder(javax.swing.BorderFactory.createTitledBorder("ID"));
        bt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_idActionPerformed(evt);
            }
        });

        bt_save.setText("Save");
        bt_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_saveActionPerformed(evt);
            }
        });

        bt_update.setText("Update");
        bt_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_updateActionPerformed(evt);
            }
        });

        bt_description.setBorder(javax.swing.BorderFactory.createTitledBorder("Description"));
        bt_description.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_descriptionActionPerformed(evt);
            }
        });

        bt_p_id.setEditable(false);
        bt_p_id.setBorder(javax.swing.BorderFactory.createTitledBorder("Professor ID"));
        bt_p_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_p_idActionPerformed(evt);
            }
        });

        cb_p_name.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_p_nameItemStateChanged(evt);
            }
        });
        cb_p_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_p_nameActionPerformed(evt);
            }
        });

        bt_clear.setText("Clear");
        bt_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_clearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(bt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bt_update, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(bt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)
                                .addComponent(bt_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_save, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bt_p_id, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cb_p_name, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bt_clear))
                            .addComponent(bt_description))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(bt_save)
                            .addComponent(bt_delete)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(bt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_update))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_description, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_p_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(bt_clear))
                            .addComponent(cb_p_name))
                        .addGap(1, 1, 1)))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_deleteActionPerformed
        Remove();
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_deleteActionPerformed

    private void bt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_nameActionPerformed

    private void subject_tableComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_subject_tableComponentAdded

    }//GEN-LAST:event_subject_tableComponentAdded

    private void bt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_idActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        ProfessorList();
        List();
        cb_p_name.setSelectedIndex(-1);
    }//GEN-LAST:event_formWindowOpened

    private void bt_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_saveActionPerformed
        Save();
    }//GEN-LAST:event_bt_saveActionPerformed

    private void subject_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subject_tableMouseClicked
        bt_id.setText(String.valueOf(subject_table.getValueAt(subject_table.getSelectedRow(), 0)));
        bt_name.setText(String.valueOf(subject_table.getValueAt(subject_table.getSelectedRow(), 1)));
        bt_description.setText(String.valueOf(subject_table.getValueAt(subject_table.getSelectedRow(), 2)));
        bt_p_id.setText(String.valueOf(subject_table.getValueAt(subject_table.getSelectedRow(), 3)));
    }//GEN-LAST:event_subject_tableMouseClicked

    private void bt_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_updateActionPerformed
        Update();
    }//GEN-LAST:event_bt_updateActionPerformed

    private void bt_descriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_descriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_descriptionActionPerformed

    private void bt_p_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_p_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_p_idActionPerformed

    private void cb_p_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_p_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_p_nameActionPerformed

    private void cb_p_nameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_p_nameItemStateChanged
        bt_p_id.setText(String.valueOf(cb_p_id.getItemAt(cb_p_name.getSelectedIndex())));
        
    }//GEN-LAST:event_cb_p_nameItemStateChanged

    private void bt_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_clearActionPerformed
        Clear();
    }//GEN-LAST:event_bt_clearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubjectW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubjectW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubjectW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubjectW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SubjectW dialog = new SubjectW(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_clear;
    private javax.swing.JButton bt_delete;
    private javax.swing.JTextField bt_description;
    private javax.swing.JTextField bt_id;
    private javax.swing.JTextField bt_name;
    private javax.swing.JTextField bt_p_id;
    private javax.swing.JButton bt_save;
    private javax.swing.JButton bt_update;
    private javax.swing.JComboBox<String> cb_p_id;
    private javax.swing.JComboBox<String> cb_p_name;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable subject_table;
    // End of variables declaration//GEN-END:variables
    void Save(){
        try{
            Subject student = new Subject();
            student.setSu_name(bt_name.getText());
            student.setSu_description(bt_description.getText());
            
            if(bt_p_id.getText().equals("null")){
                student.setP_id(null);
            }
            else
                student.setP_id(Integer.parseInt(bt_p_id.getText()));
            SubjectQ q = new SubjectQ();
            q.AddSubject(student);
            List();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
    }
    
    void List(){
        try{
            Subject student = new Subject();
            SubjectQ q = new SubjectQ();
            List<Subject> list= q.ListSubjects();
            DefaultTableModel model = (DefaultTableModel)subject_table.getModel();
            model.setRowCount(0);
            for(Subject s : list){
                model.addRow(new Object[]{s.getSu_id(),s.getSu_name(),s.getSu_description(),s.getP_id()});
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
    }
    void Remove(){
        try{
            Subject student = new Subject();
            student.setSu_id(Integer.parseInt(bt_id.getText()));
            SubjectQ q = new SubjectQ();
            q.RemoveSubject(student);
            List();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
    }
    void Update(){
        try{
            Subject student = new Subject();
            student.setSu_id(Integer.parseInt(bt_id.getText()));
            student.setSu_description(bt_description.getText());
            student.setSu_name(bt_name.getText());
            student.setP_id(Integer.parseInt(bt_p_id.getText()));
            SubjectQ s = new SubjectQ();
            s.UpdateSubject(student);
            List();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }
    
    void ProfessorList(){
        try{
            Professor professor = new Professor();
            ProfessorQ q = new ProfessorQ();
            List<Professor> list= q.ListProfessors();
            DefaultTableModel model = (DefaultTableModel)subject_table.getModel();
            model.setRowCount(0);
            for(Professor p : list){
                cb_p_name.addItem(p.getP_name());
                cb_p_id.addItem(String.valueOf(p.getP_id()));
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }
    void Clear(){
        bt_name.setText("");
        bt_id.setText("");
        bt_description.setText("");
        cb_p_name.setSelectedIndex(-1);
        bt_p_id.setText("null");
    }
}
